#! /bin/bash

# A simple script to 'git push' the project and update its 'last updated' time
sed -i "s/Last updated .\{3\} .\{3\} [0-9]\{1,\} [0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\} P.T [0-9]\{4\}/Last updated `date +"%m-%d-%y, at %H:%M:%S"`/" ./index.html
git add ./index.html
git commit --amend --no-edit
git push origin master
